weave-service-spring introduce HttpServletRequestWrapper
to avoid
java.lang.IllegalStateException: getInputStream() has already been called for this request